// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckqscxtkwxbbcdwldwia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrcXNjeHRrd3hiYmNkd2xkd2lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMjg3NTIsImV4cCI6MjA1NDcwNDc1Mn0.DJZDb4qjF0JdbmKvUDdnvsneu6fq874paLxOB3r7RGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);